### ISSUE TITLE
ModuleNotFoundError: No module named 'fromedi'

### ISSUE THREAD

**Issue by ZAJDAN** [tanialx/fromedi#6]
I just downloaded the package, unziped and trying the test. Returns:
```
C:\fromedi-main\tests>py test_parser.py
Traceback (most recent call last):
  File "C:\Users\zchladek\Downloads\fromedi-main\fromedi-main\tests\test_parser.py", line 1, in <module>
    from fromedi.parser import Parser
ModuleNotFoundError: No module named 'fromedi'
```
should I install anything next?
I am using Python3 on windows.

**Comment by tanialx** [comment]
Hello @ZAJDAN,

To run tests, please run `python -m pytest` in the project root dir (fromedi-main in your case). You should have installed `pytest` prior to that

That would be enough to get it working. Please refer to [updated README](https://github.com/tanialx/fromedi#development) for more details
